# Generated by Django 5.1.7 on 2025-03-15 14:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/profile.png', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
