# Generated by Django 5.1.7 on 2025-03-21 12:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=accounts.models.product_image_path)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('smartphone', 'Smartphone'), ('accessory', 'Accessory'), ('tv', 'TV')], default='laptop', max_length=50)),
            ],
        ),
    ]
